apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
    tier: back
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: postgres
    name: postgres
  selector:
    app: db
---
apiVersion: v1
kind: Service
metadata:
  name: db-headless
  labels:
    app: db
    tier: back
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 5432
    targetPort: postgres
    name: postgres
  selector:
    app: db
