apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
namespace: prod
commonAnnotations:
  supported-by: demo.example.com
labels:
- includeSelectors: false
  pairs:
    project: vote-demo
patches:
- path: service.yaml
- path: preview-service.yaml
- path: rollout.yaml

