apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

commonAnnotations:
  supported-by: demo.example.com

labels:
- includeSelectors: false
  pairs:
    project: vote-demo

resources:
- ../../base

patches:
- path: strategy-canary-patch.yaml
