apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
    tier: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        tier: back
    spec:
      containers:
      - name: db
        image: postgres:15-alpine
        envFrom:
        - secretRef:
            name: db-secret
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data-pvc
