apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
    tier: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        tier: back
    spec:
      containers:
      - name: worker
        image: <image>:v1
