name: Hello World Self Hosted

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - name: Print Hello World
        run: echo "Hello from Self Hosted Runner!"
